title: Hola, gracias por visitar mi blog!
author: Mathias
email: flialopez18@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  En este blog voy a mostrar mis trabajos y demostrar lo mucho que me apasiona la programación.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  morsasoftware # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
